// Generated by insterra

module "digitalocean_compute_deneb_lnq" {
  source  = "upmaru/instellar/digitalocean"
  version = "0.5.2"

  cluster_topology = [
  ]

  identifier   = "deneb-lnq"
  node_size    = "s-1vcpu-1gb-amd"
  ssh_keys     = ["zack-mac-studio"]
  storage_size = 15
  vpc_id       = module.digitalocean_networking_deneb_oqc.vpc_id
  vpc_ip_range = module.digitalocean_networking_deneb_oqc.vpc_ip_range
}
