// Generated by insterra

variable "instellar_auth_token" {}
variable "instellar_host" {}
provider "instellar" {
  auth_token = var.instellar_auth_token
  host       = var.instellar_host
}

variable "do_access_key" {}
variable "do_secret_key" {}
variable "do_token" {}
provider "digitalocean" {
  spaces_access_id  = var.do_access_key
  spaces_secret_key = var.do_secret_key
  token             = var.do_token
}
